[package]
name = "rust_diff"
version = "0.1.0"
authors = ["Michael Donovan <mbdono56@gmail.com>"]

[lib]
name = "libdiff"
path = "src/libdiff.rs"

[[bin]]
name = "diff"
path = "src/bin/diff.rs"

[dependencies]
